server:
  port: 8080

# 线程池配置
thread:
  pool:
    executor:
      config:
        core-pool-size: 20
        max-pool-size: 50
        keep-alive-time: 5000
        block-queue-size: 5000
        policy: CallerRunsPolicy


spring:
  datasource:
    username: root
    password: xmzpassword
    url: jdbc:mysql://47.117.163.255:3306/ai-agent-station?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000
  main:
    allow-bean-definition-overriding: true
  #  main:
  #    banner-mode: off
  #    web-application-type: none
  ai:
    #    mcp:
    #      client:
    #        request-timeout: 180
    #        sse:
    #          connections:
    #            server1:
    #              url: http://localhost:8082
    #            server2:
    #              url: http://localhost:8081

    #        stdio:
    #          servers-configuration: classpath:/mcp-servers-config-2.json
    # 个人配置，通过 http://127.0.0.1:8090 代理出去
    vectorstore:
      pgvector:
        datasource:
          driver-class-name: org.postgresql.Driver
          username: postgres
          password: postgres
          url: jdbc:postgresql://14.103.155.193:5432/springai
          type: com.zaxxer.hikari.HikariDataSource
          hikari:
            maximum-pool-size: 5
            minimum-idle: 2
            idle-timeout: 30000
            connection-timeout: 30000
    openai:
      base-url: https://apis.itedus.cn
      api-key: sk-oFfYLM1fUVsrWFwA1fA32dDcE6A441C48b70A3D09e68CeF2



  autoconfigure:
    exclude:
      - org.springframework.ai.model.ollama.autoconfigure.OllamaEmbeddingAutoConfiguration
# 或排除 OpenAI：
#     - org.springframework.ai.model.openai.autoconfigure.OpenAiEmbeddingAutoConfiguration


# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml